title: "HackScale Blog"
description: "Cybersecurity tutorials, red teaming, and ethical hacking writeups."
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

url: "https://hackscaleblog.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

author:
  name: "HackScale"
  avatar: "/assets/images/avatar.png"
  bio: "Cybersecurity researcher sharing tutorials & writeups."
  location: "Internet"
  links:
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://youtube.com/@Hack_Skill"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/HackScaleTeam"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

collections:
  posts:
    output: true
