title: "HackScale Blog"
description: "Cybersecurity tutorials, writeups, and hands-on labs"
url: "https://hackscaleblog.github.io"
baseurl: ""
theme: null

# Only safe plugins allowed by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "HackScale"
  bio: "Ethical hacking & red teaming tutorials"
  email: "hackscale@gmail.com"

paginate: 6
timezone: UTC

# Navigation links
nav:
  - title: Home
    url: /
  - title: Tutorials
    url: /categories/tutorial/
  - title: Writeups
    url: /categories/writeup/
  - title: About
    url: /about/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
